version: '3.8'

services:
  checker-cpp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-cpp:latest
    container_name: checker-cpp-build
    
  checker-python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-python:latest
    container_name: checker-python-build

  checker-java:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-java:latest
    container_name: checker-java-build

  checker-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-nodejs:latest
    container_name: checker-nodejs-build

  checker-csharp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-csharp:latest
    container_name: checker-csharp-build

  checker-go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCRIPT_NAME: runner.sh
    image: checker-go:latest
    container_name: checker-go-build
